### ISSUE TITLE
Incompatibility with elytradev's mod

### ISSUE THREAD

**Issue by Brycey92** [Yeregorix/Mirage#11]
[Here](https://gist.github.com/Brycey92/5233e8ef43c9010a68fd692aaa044c9d) is the crash report. I'm not sure whether this is an issue with Mirage or something else, because the crash stops when Mirage is removed, but you are not elytradev.

**Comment by Yeregorix** [comment]
At the next update I will publish a second jar with a different identifier, this should fix your issue.

**Comment by Yeregorix** [comment]
This issue should now be fixed if you download the jar files [here](https://files.smoofyuniverse.net/smoofymirage/) instead of on the ore page. Feel free to re-open this issue if it's not the case.
