### ISSUE TITLE
Error message with spongeforge-1.12.2-2705-7.1.0-BETA-3361

### ISSUE THREAD

**Issue by superwizzman** [Yeregorix/Mirage#12]
Hi, I install mirage in my folder plugins, sponge detect my plugin when I do the command /sponge plugins,  but the plugin do not work. When I take a xray texture pack I see the minerals correctly. Also, I have an error message with mirage when the server is running.

Error message: https://www.dropbox.com/s/4toz27rc6x34pyg/latest.log?dl=1
Sorry is not on pastebin because I exceeded the maximum paste size of 512 kilobytes per paste.
Thank you!

ps: Sorry for my ban english I'm a quebecer.

**Comment by Yeregorix** [comment]
[ENGLISH]
`!!WARNING!! Mirage was not loaded correctly. Be sure that the jar file is at the root of your mods folder!` Line 340
I speak french if it can help you. If you need more help feel free to ask.

[FRENCH]
`!!ATTENTION!! Mirage n'a pas été chargé correctement. Assure toi que le fichier jar est bien à la racine du répertoire du dossier des mods!` Ligne 340
Je parle français si ca peut t'aider. Si tu as besoin de plus d'aide n'hésite pas.

**Comment by superwizzman** [comment]
Oh super c'est rare un français dans le monde des plugins sur minecraft! :D Je l'avais mis dans le sous-dossier plugins (mods/plugins). Je ne savais pas qu'il fallait le mettre dans le dossier mods. Je vais essayer ça merci!

**Comment by Yeregorix** [comment]
Je l'ai écrit sur la page du plugin mais c'est pas grave, je vais essayer de le rendre plus explicite ^^. Je ferme l'issue, si tu as toujours n'hésite pas à la rouvrir.

**Comment by superwizzman** [comment]
Ok merci! Tu pourrais mettre une section français ça serait
révolutionnaire! :p

Le jeu. 20 sept. 2018 à 13:39, Yeregorix <notifications@github.com> a
écrit :
