### ISSUE TITLE
[FR] Conflit entre plugins et mods

### ISSUE THREAD

**Issue by WareZ57** [Yeregorix/Mirage#14]
Bonjour, 

J'ai décidé d'utiliser votre plugin (il y a pas vraiment d'autre choix :) )

Mais celui-ci rentre en conflit avec un autre plugin et un mods (je comprend pas du comment n'y du pourquoi)

Le plugin en question " Skinsrestorer "
https://www.spigotmc.org/resources/skinsrestorer.2124/
Le mod : 
https://minecraft.curseforge.com/projects/plants
[crash-2018-10-01_10.15.15-server.txt](https://github.com/Yeregorix/Mirage/files/2433221/crash-2018-10-01_10.15.15-server.txt)
[crash-2018-10-01_10.34.39-server.txt](https://github.com/Yeregorix/Mirage/files/2433222/crash-2018-10-01_10.34.39-server.txt)

Ci-joins le crash error du serveur.

Dois-je passé par vous ou vers l'auteur de skinsrestorer pour ce bug ?

Merci bonne journée !

Minecraft 1.12.2
SpongeAPI 7.1.0-ff990df
SpongeForge 1.12.2-2705-7.1.0-BETA-3448
Forge 14.23.4.2759

**Comment by Yeregorix** [comment]
Je vais regarder quel est le problème, je te dirais ensuite s'il faut mieux passer par moi ou par l'auteur du plugin ^^ Peux tu me donner les logs complets ? Cela m'aiderait beaucoup à comprendre.

**Comment by WareZ57** [comment]
Merci de la réponse RAPIDE !

Malheureusement mis à part les crash errors je ne peux pas fournir plus 😞 

Je vais voir ce que je peux avoir de plus !

**Comment by WareZ57** [comment]
Voilà l'erreur console que j'ai : https://pastebin.com/Eq9mtT0d

**Comment by Yeregorix** [comment]
J'ai identifié le problème avec Plants 2, ce sera corrigé dans la prochaine mise à jour. Pour le problème avec SkinRestorer il semblerait que ce soit lié à Bstats, je vais continuer de me renseigner.

**Comment by WareZ57** [comment]
Super ! Très content de la nouvelle Merci !  Pour le moment aucune nouvelle
du coter de skinrestorer & plant2 !

**Comment by Yeregorix** [comment]
J'ai publié une mise à jour sur Ore. Le problème avec Plants 2 devrait être fixé et pour bStats, l'implémentation a été totalement mise à jour donc je ne vois pas de raison que le problème avec SkinRestorer soit toujours d'actualité. Si tu as toujours un problème n'hésite pas à rouvrir cette issue ou une autre.
