### ISSUE TITLE
Passive mobs do not move

### ISSUE THREAD

**Issue by ItsiAdam** [Yeregorix/Mirage#16]
When running SpongeForge 2768-7.1.4 and Forge 2768 with no mods/plugins except Mirage, running all default configs, no passive mobs move. 
Random turning/player focus still works, and chickens still lay eggs.

This still happens with Mirage disabled per world.

[debug.log](https://github.com/Yeregorix/Mirage/files/2705824/debug.log)
[latest.log](https://github.com/Yeregorix/Mirage/files/2705825/latest.log)

**Comment by Yeregorix** [comment]
It's strange. Mirage normally does nothing special in relation to the entities. The only thing that could explain this problem would be a drop in performance but I can't find almost anything related to Mirage in your Timings. Do you have the same problem without Mirage? Can you send me a Spark report? They are sometimes more useful.

**Comment by ItsiAdam** [comment]
No, the issue is only present with Mirage.
Heap: https://sparkprofiler.github.io/?aJ3asO9cwy
Profile: https://sparkprofiler.github.io/?YfdHOOLDiv

**Comment by Yeregorix** [comment]
I identified the problem, I'm working on a fix.
