### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by XakepSDK** [Yeregorix/Mirage#19]
1. Forge version: forge-1.12.2-14.23.5.2815-universal
2. Sponge version: spongeforge-1.12.2-2768-7.1.6-RC3624
3. Log: https://gist.github.com/XakepSDK/46c990a23fe2b8affdc6bc56290ebc1b

**Comment by Yeregorix** [comment]
The recent block tracking refactor in SF 1.12.2-2768-7.1.6-RC3618 broke a method signature. I have the fix, the update will be published soon.

**Comment by Yeregorix** [comment]
I'm waiting for SpongeVanilla to update before pushing the fix. I need to do some tests.

**Comment by XakepSDK** [comment]
Completely unusable after SF-3616
https://github.com/SpongePowered/SpongeCommon/pull/2219
