### ISSUE TITLE
Issue loading Mirage on sponge pongeforge-1.12.2-2838-7.1.7-RC3853!

### ISSUE THREAD

**Issue by MaxIsH0t** [Yeregorix/Mirage#25]
Hello, my server is crashing because of Mirage not being updated.

SpongeForge Version: spongeforge-1.12.2-2838-7.1.7-RC3853
Forge Version: 14.23.5.2838

Crash Report: https://paste.gg/p/anonymous/b1004d799a804923a3fbe8c6befdf40f

**Comment by Yeregorix** [comment]
I forgot to publish the custom jar . I will do it in the day.

**Comment by Yeregorix** [comment]
Done. https://files.smoofyuniverse.net/smoofymirage/ :)
