### ISSUE TITLE
Incompatibility with Phospor

### ISSUE THREAD

**Issue by Dhannyjsb** [Yeregorix/Mirage#27]
Server Crash on startup if Using forge-1.12.2-14.23.5.2838-universal.jar + spongeforge-1.12.2-2838-7.1.7-RC3880.jar + phosphor-1.12.2-0.2.6_build50-universal.jar +  Mirage-1.3.10.jar 

https://pastebin.com/w44NEwSa

**Comment by Yeregorix** [comment]
I will take a look as soon as I can. I keep you updated. :)

**Comment by Dhannyjsb** [comment]
Thanks for fast response. I hope you have a nice day :)

**Comment by Yeregorix** [comment]
The issue has been fixed. I will publish a new release soon.
