### ISSUE TITLE
Incompatibility with ic2

### ISSUE THREAD

**Issue by zsn741656478** [Yeregorix/Mirage#29]
https://paste.ubuntu.com/p/FSz3GcbkjG/

Crash when the server starts. May not be compatible with ic2 ?

**Comment by Yeregorix** [comment]
Two things:
- Mirage 1.3.10 require SpongeForge/SpongeVanilla 7.1.7 (you're using 7.1.6)

- Mirage is currently incompatible with Phosphor. I will publish a new release very soon to fix this.
