### ISSUE TITLE
Port To Forge

### ISSUE THREAD

**Issue by projectrpgmv** [Yeregorix/Mirage#30]
any plan for port to forge without sponge ?
I think few people doesn't like sponge.

**Comment by Yeregorix** [comment]
I'm busy these days so it won't happen soon but I will think about it when updating to 1.14.

**Comment by Yeregorix** [comment]
When Sponge for MC 1.14 is released, my priority will be to update Mirage as soon as possible. I will focus on having a great integration with Sponge. If the project structure allows me to do a Forge only version easily I will do it but it's very unlikely possible. I would prefer to concentrate on one implementation. This project is opensource, if someone wants to port it to Forge himself, he can.
