### ISSUE TITLE
OpenComputers screen facing/merging problem

### ISSUE THREAD

**Issue by electron93** [Yeregorix/Mirage#31]
- SpongeForge 1.12.2-2838-7.1.7-RC3903
 - Mirage-1.3.11 **AND** OpenComputers-MC1.12.2-1.7.4.153

![2019-08-29_22 03 36](https://user-images.githubusercontent.com/1076914/63978941-50d24580-cac0-11e9-93ac-86be730d3786.png)

**Comment by Yeregorix** [comment]
I just identified the issue. There is a conflict between an optimization added by my plugin and Forge's extended block states. I'm working on a fix.
