### ISSUE TITLE
Mixin crash caused by outdated SF

### ISSUE THREAD

**Issue by Nbgreen** [Yeregorix/Mirage#32]
server crashes and doesn't run when I add the plugin to the server 
crash report https://paste.dimdev.org/ozigufagig.rb

**Comment by electron93** [comment]
@Nbgreen, the latest version of Mirage depends on **SpongeForge 7.1.7**, the problem is caused by the outdated **SpongeForge 7.1.6** that you are using. Update SpongeForge or [grab an older version of Mirage](https://ore.spongepowered.org/Yeregorix/Mirage/versions).
