### ISSUE TITLE
The server must require the Mirage mod to enter

### ISSUE THREAD

**Issue by ChukiStrike** [Yeregorix/Mirage#34]
I've seen that if the player doesn't have the Mirage mod in his own mod folder, the xray still works. Therefore it must require the server to have the Mirage mod in order to enter. But it doesn't.

**Comment by electron93** [comment]
@ChukiStrike This is not anti-cheat for the client side. This is a plugin for Sponge, designed to work without installing anything on the client.

**Comment by ChukiStrike** [comment]
Now works only in server. Thanks you.
