### ISSUE TITLE
Specifying BlockTypes in configuration

### ISSUE THREAD

**Issue by sidyhe** [Yeregorix/Mirage#35]
sponge 7.1.9
mirage 1.3.13
minecraft 1.12.2

Hi!
I am trying to hide others mod's ore
found that mirage only hide the ore with data 0
there are different ores, to gain them by server console, type this

```
/give @p forestry:resources 64 0
/give @p forestry:resources 64 1
```

so there are two kinds of ores, how to **hide ore with all data** ?

my config is here:
```
Modifiers=[
    {
        Options {
            # Blocks that will be hidden by the modifier
            Blocks=[
                "forestry:resources"
            ]
            # The maximum Y of the section to obfuscate
            MaxY=255
            # The minimum Y of the section to obfuscate
            MinY=0
            # The block used to replace hidden blocks
            Replacement="minecraft:stone[variant=stone]"
        }
        Type=obvious
    }
]
```

**Comment by Yeregorix** [comment]
`forestry:resources` should theoretically already targets all variants. I will do some tests as soon as I can to verify that.
