### ISSUE TITLE
Crash with SpongeForge 1.12.2-2838-7.1.9

### ISSUE THREAD

**Issue by Haibane-Kira** [Yeregorix/Mirage#36]
Can't start server if using mirage with updated sponge (1.12.2-2838-7.1.9)
Works fine with 1.12.2-2838-7.1.8
Any fixes? :<

**Comment by Yeregorix** [comment]
Can you send me your logs using a service such as pastebin ?

**Comment by Yeregorix** [comment]
I've published an update with some fixes. Try updating and reopen this issue it persists
