### ISSUE TITLE
NPE when entering The Twilight Forest

### ISSUE THREAD

**Issue by Anytinz** [Yeregorix/Mirage#37]
Entering the world created by "The Twilight Forest" will cause the server to crash. Disabling Mirage will not happen.
[crash-2020-03-21_16.54.09-server.txt](https://github.com/Yeregorix/Mirage/files/4362624/crash-2020-03-21_16.54.09-server.txt)

**Comment by Yeregorix** [comment]
Thanks for reporting the issue. I will investigate to find the cause of the problem.

**Comment by Yeregorix** [comment]
Your issue has been fixed in the latest version.
