### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by Invidious** [Yeregorix/Mirage#38]
Placed in mods folder and crashes on start. Remove plugin and its works fine

[debug.log](https://github.com/Yeregorix/Mirage/files/4399809/debug.log)
[latest.log](https://github.com/Yeregorix/Mirage/files/4399811/latest.log)

**Comment by Yeregorix** [comment]
Can you send me a server archive with the minimal setup to reproduce the issue?

**Comment by Yeregorix** [comment]
I'm closing this issue but feel free to reopen if it persists and you have an archive.
