### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by bigenergy** [Yeregorix/Mirage#39]
https://pastebin.com/GBiQ1EWz
Mirage 1.3.15
spongeforge-1.12.2-2838-7.1.11-RC4007

**Comment by Yeregorix** [comment]
Please provide the full logs, there is a lot of information in the non spam part that I need to understand the issue.

**Comment by Yeregorix** [comment]
I'm closing this issue but feel free to reopen if it persists and you have logs.
