### ISSUE TITLE
Duplicate of #11 (3)

### ISSUE THREAD

**Issue by nacjm** [Yeregorix/Mirage#40]
Hey, 
I had my server crash with this exact error.
https://gist.github.com/nacjm/4f1e337ff9103ce30e326a266eed9a68
Any ideas what is causing it?

**Comment by Yeregorix** [comment]
My plugin and elytradev's mod are conflicting because they have the same name. Please use jars downloaded from https://files.smoofyuniverse.net/smoofymirage/ instead of the Ore page to resolve the issue.
