### ISSUE TITLE
Regex usage for Blocks[] list?

### ISSUE THREAD

**Issue by Haibane-Kira** [Yeregorix/Mirage#42]
Is there any way or feature to filter blocks with regex?
While adding any new mod with hundred of ores or any other blocks causes pretty problematic time to catch and list them all...

**Comment by Yeregorix** [comment]
That's an interesting proposal I will see what I can do about that and keep you updated. 🙂

**Comment by Yeregorix** [comment]
That's technically possible to implement however once the config loaded, the regex will be replaced by its result.
