### ISSUE TITLE
any plan to support bukkit ?

### ISSUE THREAD

**Issue by sidyhe** [Yeregorix/Mirage#45]
hello!
any plan to support bukkit?

**Comment by Yeregorix** [comment]
Mirage heavily uses Mixin to modify parts of the server code which is not possible on Bukkit unless shipping a custom Mixin setup. Which is probably not simple. I left Bukkit platform long ago and I wouldn't be able to port Mirage myself nor have the time to. Mirage is open source, if someone else wants to port Mirage to Bukkit or whatever platform, he can.
