### ISSUE TITLE
Mirage Anti-Xray plugin not working, crashes server on startup.

### ISSUE THREAD

**Issue by 1Kyro** [Yeregorix/Mirage#48]
I know that this is what's causing it because I tried installing my plugins one by one to see what was making my server throw errors and then crash. I play on the modpack "FTB - Revelations". I've tried a few different things but can't seem to fix it. I don't know what else to add, please help me out.

Here is the server crash-log:
https://pastebin.com/S7rEBbpW

Let me know if there is something else I should add.

**Comment by Yeregorix** [comment]
You're using a really old (1,5 year) version (1.3.9). Please update to the latest version (1.3.17) and reopen this issue if the problem persists.
