### ISSUE TITLE
TrackingUtil method change causes the server to crash

### ISSUE THREAD

**Issue by yaroslav4167** [Yeregorix/Mirage#7]
SpongeForge version: 1.12.2-2705-7.1.0-BETA-3248

[Crash report](https://pastebin.com/JEaa2yfQ)

**Comment by yaroslav4167** [comment]
OK, thank you.

**Comment by Yeregorix** [comment]
The issue has been fixed. I need to do some tests and then I will publish a new release.

**Comment by yaroslav4167** [comment]
I have no problems. Checked with github-version.
Thank you.
